name: Build Fabric mod with Gradle
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4
    - name: Extract build version information
      id: ref
      run: .github/extract_refs.sh
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        check-latest: true
    - name: Initialize caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/loom-cache
          ~/.gradle/wrapper
        key: ${{ runner.os }}-build-fabric-${{ steps.ref.outputs.minecraft_version }}
        restore-keys: |
          ${{ runner.os }}-build-fabric-
    - name: Compile with Gradle
      run: ./gradlew build
    - name: Upload compiled artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WFGM-artifacts-${{ steps.ref.outputs.branch }}
        path: build/libs/*.jar
